=== Edoukou-Aman/Projet_DSB/basededonnees.dtd
<!ELEMENT basededonnees (listeFilm,listeGenre)>
<!ELEMENT nom(#PCDATA)>
<!ELEMENT listeFilm(FILM)*>
<!ELEMENT FILM (GENREREF+, descriptionx?)>
<!ATTLIST FILM idFilm ID #REQUIRED titre CDATA #REQUIRED description CDATA #IMPLIED realisateur CDATA #IMPLIED duree CDATA #required restriction #IMPLIED >

<!ELEMENT GENREREF>
<!ATTLIST idGenre IDREF #REQUIRED>

<!ELEMENT infoFilm>

<!ELEMENT listeGenre (GENRE)*
<!ELEMENT GENRE>
<!ATTLIST GENRE idGenre ID #REQUIRED nom CDATA #REQUIRED>

<!ELEMENT descriptionx (#PCDATA|url)*>
<!ELEMENT url (#PCDATA)>
<!ATTLIST descriptionx date #IMPLIED auteur #IMPLIED>
<!ELEMENT item ANY>

=== Edoukou-Aman/Projet_DSB/basededonnees.xml
<?xml version="1.0"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE basededonnees SYSTEM "basededonnees.dtd">
<basededonnees>
	<listeFilm>
		<FILM idFilm="FFG3" titre="Forrest Gump" description="..." realisateur="..." duree="...">
			<GENREREF id="GANIM"> </GENREREF>

			<descriptionx date="19/03/2021"> 
				DESCRIPTION
			</descriptionx>
		</FILM>

		<FILM idFilm="FFRT" titre="FRT" description="..." realisateur="..." duree="...">
			<GENREREF id="Horreur"> </GENREREF>
			<descriptionx auteur="gtesd"> 
				<url>Lien</url>
				</descriptionx>	
		</FILM>
		
		<FILM idFilm="FDSF" titre="DSF" description="..." realisateur="..." duree="...">
			<GENREREF id="ComÃ©die"> </GENREREF>	
		</FILM>

	</listeFilm>
</basededonnees>
